# Generated by Django 3.1 on 2021-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0002_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
