# Generated by Django 3.1 on 2021-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0004_auto_20210522_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
