# Generated by Django 3.1 on 2021-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0005_auto_20210522_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
