# # Generated by Django 3.1 on 2021-05-22 19:26

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('helpapp', '0006_auto_20210522_2349'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='image',
#             name='mob',
#             field=models.CharField(max_length=200, null=True),
#         ),
#     ]
