# Generated by Django 3.1 on 2021-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0008_auto_20210523_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='need',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
