# # Generated by Django 3.1 on 2021-05-23 10:17

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('helpapp', '0009_image_need'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='image',
#             name='map',
#             field=models.URLField(null=True),
#         ),
#     ]
