# Generated by Django 3.1 on 2021-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0010_image_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mob',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
